spring:
  application:
    name: SMS

  datasource:
    url: jdbc:postgresql://172.236.144.75:5432/SMS_DB
    username: postgres
    password: SMS_2025
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      timeout: 60000
      host: 172.236.144.75
      port: 6379