spring:
  application:
    name: SMS

  datasource:
    url: jdbc:postgresql://172.236.144.75:5432/SMS_DB
    username: postgres
    password: SMS_2025
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true